### ISSUE TITLE
Freezes micro on saving a zig file.

### ISSUE THREAD

**Issue by Jankoy** [squeek502/micro-zigfmt#2]
Just doesn't work, no error messages or anything, micro just freezes up on saving a zig file, I tried an empty file too with a .zig extension, and the same thing.

**Comment by Jankoy** [comment]
Nevermind, it just started working for some reason right after I made this issue.

**Comment by squeek502** [comment]
This is because Zig now compiles `zig fmt` from source on-demand rather than it being built into the compiler exeuctable, so the first time you run `zig fmt` it has to compile it. After that it will be cached.

Relevant Zig issues if you're curious:
- https://github.com/ziglang/zig/issues/19063
- https://github.com/ziglang/zig/pull/19102

**Comment by Jankoy** [comment]
I see, thanks for explaining.
